In [2]:
pip install torch

   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
    --------------------------------------- 2.1/114.6 MB 20.8 MB/s eta 0:00:06
   --- ------------------------------------ 8.9/114.6 MB 26.3 MB/s eta 0:00:05
   ----- ---------------------------------- 16.3/114.6 MB 30.2 MB/s eta 0:00:04
   ------- -------------------------------- 20.7/114.6 MB 28.7 MB/s eta 0:00:04
   --------- ------------------------------ 28.0/114.6 MB 29.5 MB/s eta 0:00:03
   ------------ --------------------------- 35.4/114.6 MB 30.8 MB/s eta 0:00:03
   -------------- ------------------------- 41.7/114.6 MB 30.8 MB/s eta 0:00:03
   ---------------- ----------------------- 47.4/114.6 MB 30.4 MB/s eta 0:00:03
   ------------------ --------------------- 52.2/114.6 MB 29.7 MB/s eta 0:00:03
   -------------------- ------------------- 58.7/114.6 MB 29.8 MB/s eta 0:00:02
   ---------------------- ----------------- 65.3/114.6 MB 30.1 MB/s eta 0:00:02
   ------------------------- -------------- 73.4/11


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import torch

scaler = torch.tensor(1)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(scaler.shape, vector.shape, matrix.shape)
print(scaler.dtype, vector.dtype, matrix.dtype)

torch.Size([]) torch.Size([3]) torch.Size([3, 2])
torch.int64 torch.int64 torch.int64


In [ ]:
print(torch.zeros(2, 3))
print(torch.arange(5, 15, 2))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([ 5,  7,  9, 11, 13])
tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])
